spring:
  profiles:
    active: test

---
server:
  port: 8090
spring:
  profiles: test
  application:
    name: eureka
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/common
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8090/eureka

